services:
  auth-api:
    build:
      context: .
      target: prod-auth-api
    ports:
      - '3002:3002'
    environment:
      AUTH_API_PORT: "3002"

  authorization-server:
    build:
      context: .
      target: prod-authorization-server
    ports:
      - '3005:3005'
    environment:
      AUTHORIZATION_SERVER_PORT: "3005"
      AUTHORIZATION_SERVER_URL: authorization-server
      LOCAL_ACCOUNT_SERVER_URL: "http://localhost:3001"
      JWT_SECRET: "secret"
      JWT_TOKEN_EXPIRES: "60s"
      MONGO_URI: mongodb://root:example@mongo
      MONGO_DB_NAME: "sell-point"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_CODE_VERIFY_EXPIRATION: "120"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:7.0.9-rc1
    ports:
      - 27017:27017
    volumes:
      - './mongodata:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:alpine3.19
    ports:
      - '6379:6379'
    volumes:
      - './redisdata:/data'
  mysql:
    image: mysql:lts
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1928374650
      MYSQL_DATABASE: sell-point
  kafka:
    image: bitnami/kafka:3.3.2
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_METADATA_MIGRATION_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  #kafdrop:
  #  image: obsidiandynamics/kafdrop
  #  restart: "no"
  #  ports:
  #    - "9000:9000"
  #  environment:
  #    KAFKA_BROKERCONNECT: "kafka:29092"
  #  depends_on:
  #    - "kafka"
  #kafka:
  #  image: obsidiandynamics/kafka
  #  restart: "no"
  #  ports:
  #    - "2181:2181"
  #    - "9092:9092"
  #  environment:
  #    KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
  #    KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  #    KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  #    KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
  #    KAFKA_RESTART_ATTEMPTS: "10"
  #    KAFKA_RESTART_DELAY: "5"
  #    ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"